### ISSUE TITLE
Language bindings for GBFS v3

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gbfs-json-schema#106]
Create TypeScript and Java language bindings for GBFS v3. Discussion initially started in #96

**Comment by davidgamez** [comment]
Tasks:
- [ ] Investigate Entur Java generated bindings: https://github.com/entur/gbfs-java-model
- [ ] Present to the team the strategy to generate bindings for Typescript and JS
- [ ] Implement biding generation(maybe we need manual steps) and documentation

Useful links:
- https://json-schema.org/implementations#generators-from-schemas
- https://github.com/entur/gbfs-java-model

**Comment by richfab** [comment]
This v3.0 feed from TIER can be used for testing the bindings: https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/

**Comment by testower** [comment]
> This v3.0 feed from TIER can be used for testing the bindings: https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/

Unfortunately it’s not been updated since 3.0-RC. E.g. timestamps are wrong format.

**Comment by richfab** [comment]
True, thank you @testower. 

The v3.0-RC feeds from this manifest can be used to test the bindings with the correct timestamp format:

- https://api.dev.entur.io/mobility/v2/gbfs/v3beta/manifest.json (ENTUR)

These other v3.0-RC feeds can also be used for testing but they have the v2.3 timestamp format:

- https://api.ridecheck.app/gbfs/v3/manifest.json (Check)
- https://data.rideflamingo.com/gbfs/3/manifest.json (Flamingo)
