### ISSUE TITLE
Support v3.1-RC in TypeScript

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs-json-schema#122]
## Context
v3.1-RC was released on May 22, 2024 (see [release notes](https://github.com/MobilityData/gbfs/releases/tag/v3.1-RC)).

## To do
Support v3.1-RC in the TypeScript model (https://github.com/MobilityData/gbfs-json-schema/tree/master/models/typescript).

**Comment by emmambd** [comment]
Looks like #130 closed this - is that correct @Alessandro100?

**Comment by Alessandro100** [comment]
it can be closed, but after testing it, I found an issue. I'll be making another branch to address the issue
