### ISSUE TITLE
Update Java model with list of time zones

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs-json-schema#148]
Follow-up of https://github.com/MobilityData/gbfs-json-schema/issues/146

## Context
The time zones in the schemas were replaced with the content of the `TZ identifier` column from [this list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).

## Problem
The Java models are inconsistent with the spec because they use the previous list of time zones.

## Solution
Update the Java models with the list of time zones from the [schemas](https://github.com/MobilityData/gbfs-json-schema/blob/master/v3.0/system_information.json#L150).

**Comment by leonardehrenfried** [comment]
You actually don't need to do much. The compiler will regenerate the types for you.

**Comment by richfab** [comment]
@leonardehrenfried Our dev team will update the Java model by the end of the month. If you need it before, feel free to open a PR if you want. Thank you!

**Comment by richfab** [comment]
@leonardehrenfried It seems that the update will happen sooner than expected. A [PR](https://github.com/MobilityData/gbfs-json-schema/pull/153) was open by @Alessandro100 ⚡
