### ISSUE TITLE
Why there is not a description of the data in system_regions schema?

### ISSUE THREAD

**Issue by albertoabellagarcia** [MobilityData/gbfs-json-schema#48]
We are using the schemas for creating an adaptation for the API [NGSI](https://en.wikipedia.org/wiki/NGSI-LD) standard in the [Smart Data Models](https://smartdatamodels.org) program and we found that there is not a description in the schema of [system_regions](https://github.com/MobilityData/gbfs-json-schema/blob/master/system_regions.json) for the property data.
Thanks

**Comment by isabelle-dr** [comment]
Thanks for flagging this! Closing this issue, this has been fixed in #58
