### ISSUE TITLE
Use integer type for integer fields

### ISSUE THREAD

**Issue by hannesj** [MobilityData/gbfs-json-schema#51]
Currently all numeric fields are specified having `"type": "number"`, while the [GBFS specification](https://github.com/NABSA/gbfs/blob/master/gbfs.md#field-types) defines most of these fileds using `Non-negative Integer`. This would be reflected better by changing this to `"type": "integer"`, which the [json schema specification allows](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.1). Also, we could utilize the [`minimum`](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.4) validation to make sure the values are non-negative.

**Comment by isabelle-dr** [comment]
Thanks for flagging this! Closing this issue, this has been fixed in #58
