### ISSUE TITLE
number types that can be integer in v2.3-RC2

### ISSUE THREAD

**Issue by testower** [MobilityData/gbfs-json-schema#68]
I think there are some new instances of fields that are defined with type "number" that can and should be type "integer" introduced in v2.3-RC2. Can we get these fixed asap?

* g_CO2_km (vehicle_types.json)
* wheel_count (vehicle_types.json)
* max_permitted_speed (vehicle_types.json)
* rated_power (vehicle_types.json)

I haven't had time to do a complete survey of the added fields yet, but writing mappers now so can update this issue as I find more.

**Comment by isabelle-dr** [comment]
Thanks for flagging this @testower. I had a look at the other fields added in V2.3-RC2, all the rest seems good. 
This is fixed in PR #69

**Comment by testower** [comment]
Thanks @isabelle-dr 🙂
