### ISSUE TITLE
misleading description in station_information

### ISSUE THREAD

**Issue by albertoabellagarcia** [MobilityData/gbfs-json-schema#77]
the original description of the schema 
"Details including system operator, system location, year implemented, URL, contact info, time zone." 
refers to the 'year implemented' but there is no such attribute in the schema (last_updated, don't think matches this description)

**Comment by mplsmitch** [comment]
That description is for the wrong endpoint, it describes `system_information.json`, not `station_information`. The year inplemented value is contained in `system_information.json#start_date`

**Comment by albertoabellagarcia** [comment]
Maybe I am wrong but I guess this schema could be wrong then? 
https://github.com/MobilityData/gbfs-json-schema/blob/master/v2.2/station_information.json
