### ISSUE TITLE
Regex for OSM opening hours

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs-json-schema#81]
As discussed in #79, we have not been able to find a regular expression that encapsulates the [OSM Opening Hours format](https://wiki.openstreetmap.org/wiki/Key:opening_hours). 

Opening this issue in case someone has a solution, and as a general reminder to keep looking for one.

**Comment by richfab** [comment]
This [comment](https://stackoverflow.com/a/49982934) (upvoted by 3 people) mentions that this format is too complex to be validated with a regex.

>I don't think a regex can handle this complex [format](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification). You will need a real parser. The OSM wiki lists several implementations:

For this reason, I would recommend to close this issue. 

A new issue could be opened in https://github.com/MobilityData/gbfs-validator, given that code seems to be required to validate OSM opening hours.
