### ISSUE TITLE
Invalid timezone (US/Central)

### ISSUE THREAD

**Issue by testower** [MobilityData/gbfs-json-schema#84]
Not sure if this is a problem with the schema or the spec, but posting it here first.

The example for v2.2 system_information as timezone `US/Central` which is not valid according to the schema.

The spec says: 

> Refer to http://en.wikipedia.org/wiki/List_of_tz_zones for a list of valid values. Example: Asia/Tokyo, America/Los_Angeles or Africa/Cairo.

`US/Central` is listed as being of Type `Link`, and links to `America/Chicago`, which is the canonical type.

It seems then that either the list of timezones is incomplete, or the spec needs to specify explicitly that only canonical types are allowed.

**Comment by testower** [comment]
@leonardehrenfried any thoughts?

**Comment by leonardehrenfried** [comment]
Wehn I added the timezones to the schema I got it originally from this list: https://nodatime.org/TimeZones?version=2022a&format=json

To me it seems that the canonical ones would be enough but since Java also understands the links/aliases, I would be ok with adding them. It will make the list significantly longer though.

**Comment by testower** [comment]
I don't really have any strong opinions on this - but it would be nice the the spec and the schema agree, and a clarification on the schema is possibly what we need.

**Comment by testower** [comment]
@mplsmitch Do you know the original intention of the spec here?

**Comment by mplsmitch** [comment]
Way back in  v1.0 we referenced the TZ database in the `timezone` field definition. 
https://github.com/MobilityData/gbfs/blob/v1.0/gbfs.md#system_informationjson
Starting with v2.0 we added `type` to all fields and listed the defined [field types](https://github.com/MobilityData/gbfs/blob/v3.0-RC/gbfs.md#field-types)  where you will find:

> Timezone - TZ timezone from the https://www.iana.org/time-zones. Timezone names never contain the space character but MAY contain an underscore. Refer to https://en.wikipedia.org/wiki/List_of_tz_zones for a list of valid values. Example: Asia/Tokyo, America/Los_Angeles or Africa/Cairo.

We've never formally supported links/aliases but it has come up in the past. The challenge with links/aliases at least here in the US we've got some really messy issues [[1.](https://en.wikipedia.org/wiki/Time_in_Indiana)] [[2.](https://en.wikipedia.org/wiki/Time_in_Arizona)]with Daylight Savings Time where the alias breaks down.

**Comment by testower** [comment]
So it seems then that the spec and schema are in agreement, and it's just the example(s) that are wrong.

**Comment by testower** [comment]
I don't reckon it's worth it to patch v2.2 just to fix that, so closing this. Thanks for the clarification!
